# Generated by Django 3.1 on 2022-07-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jenna Cloud 9 Detector', max_length=100, unique=True)),
                ('cloud_nine', models.BooleanField(default=False)),
            ],
        ),
    ]
